blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/ishuar/tfskel/blob/main/README.md
    about: Check out the documentation for usage guides and examples
  - name: ðŸ’¬ Discussions
    url: https://github.com/ishuar/tfskel/discussions
    about: Ask questions and discuss with the community
